---
functional:
  - Неавторизованный пользователь должен иметь возможность принять участвовать в тестовой игре с ботом
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность войти на сайт под своим аккаунтом 
  - Пользователь должен иметь возможность выбрать соперника - другого игрока или бота
  - Пользователь должен иметь возможность посмотреть статистику своих игр
  - Пользователь должен иметь возможность выбрать уровень сложности, тип игры, временные рамки и задачу в игре
  - Пользователь должен иметь возможность выбрать язык программирования для решения задачи в игре
  - Пользователь должен иметь возможность выбрать язык для текста задачи в игре - русский или английский
  - Пользователь должен иметь возможность признать поражение в игре
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования
  - Веб-сайт должен быть разработан оптимизирован для скорости работы
  - Сайт должен быть безопасным
  - Сайт должен иметь адаптивную верстку, чтобы он был удобным на мобильных устройствах
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - 
