---
functional:
  - Неавторизованный пользователь должен иметь возможность принять участвовать в тестовой игре с ботом
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизоваться через GitHub или Discord
  - Пользователь должен иметь возможность войти на сайт под своим аккаунтом 
  - Пользователь должен иметь возможность выбрать соперника - другого игрока или бота
  - Пользователь должен иметь возможность посмотреть статистику своих игр
  - Пользователь должен иметь возможность выбрать уровень сложности, тип игры, временные рамки и задачу в игре
  - Пользователь должен иметь возможность выбрать язык программирования для решения задачи в игре
  - Пользователь должен иметь возможность выбрать язык для текста задачи в игре - русский или английский
  - В игре должны быть доступны все популярные языки программирования
  - Пользователь должен иметь возможность признать поражение в игре
  - На сайте должен быть рейтинг игроков
  - Пользователь должен иметь возможность посмотреть статистику других игроков
  - Пользователь должен иметь возможность посмотреть записи завершенных игр
  - Пользователь должен иметь возможность создавать турниры
  - Соперники в игре должны иметь возможность общаться в чате
  - Пользователь должен иметь возможность присоединиться к созданной другим участником игре или турниру
non-functional:
  - Сайт должен быть разработан с учетом удобства использования
  - Сайт должен быть разработан оптимизирован для скорости работы
  - Сайт должен быть безопасным
  - Сайт должен быть адаптирован для мобильных устройств
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Пользователь не должен иметь возможность изменять код соперника
  - В одной игре могут принять участие только 2 игрока
  - Если один из игроков вылетел из игры, второй может продолжать играть
